name: update dependencies

on:
  schedule:
    - cron: 30 5 * * 2
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Authenticate with GitHub package registry to be able to download from private repositories
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: npm install
        run: npm install
      - name: update dependencies
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm run update-dependencies
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "updated dependencies"
          git pull
          git push
